package locators;

//locator class is public static final which means it can be accessed by all and cannot be changed.

public class Assessment_loc {
	public final static String RECNEXTBTN = "btn-recipient";
	public final static String RECSELFRADIO = "reciepent";
	public final static String RECLOVEDONERADIO = "your-reciepent";
	public final static String SAFETYNEXTBTN = "btn-safety";
	public final static String SAFETYFIRSTRADIO = "//input[@name='Safety' and @value='1']";
	public final static String SAFETYSECONDRADIO = "//input[@name='Safety' and @value='2']";
	public final static String SAFETYTHIRDRADIO = "//input[@name='Safety' and @value='3']";
	public final static String SAFETYFOURTHRADIO = "//input[@name='Safety' and @value='4']";
	public final static String MOBNEXTBTN = "btn-mobility";
	public final static String MOBFIRSTRADIO = "//input[@name='Mobility' and @value='1']";
	public final static String MOBSECONDRADIO = "//input[@name='Mobility' and @value='2']";
	public final static String MOBTHIRDRADIO = "//input[@name='Mobility' and @value='3']";
	public final static String MOBFOURTHRADIO = "//input[@name='Mobility' and @value='4']";
	public final static String TRANSNEXTBTN = "btn-transportation";
	public final static String TRANSFIRSTRADIO = "//input[@name='Transportation' and @value='1']";
	public final static String TRANSSECONDRADIO = "//input[@name='Transportation' and @value='2']";
	public final static String TRANSTHIRDRADIO = "//input[@name='Transportation' and @value='3']";
	public final static String TRANSFOURTHRADIO = "//input[@name='Transportation' and @value='4']";
	public final static String HSKPNGNEXTBTN = "btn-housekeeping";
	public final static String HSKPNGFIRSTRADIO = "//input[@name='Housekeeping' and @value='1']";
	public final static String HSKPNGSECONDRADIO = "//input[@name='Housekeeping' and @value='2']";
	public final static String HSKPNGTHIRDRADIO = "//input[@name='Housekeeping' and @value='3']";
	public final static String HSKPNGFOURTHRADIO = "//input[@name='Housekeeping' and @value='4']";
	public final static String NUTNEXTBTN = "btn-nutrition";
	public final static String NUTFIRSTRADIO = "//input[@name='Nutrition' and @value='1']";
	public final static String NUTSECONDRADIO = "//input[@name='Nutrition' and @value='2']";
	public final static String NUTTHIRDRADIO = "//input[@name='Nutrition' and @value='3']";
	public final static String NUTFOURTHRADIO = "//input[@name='Nutrition' and @value='4']";
	public final static String GROOMHYGNEXTBTN = "btn-groomingandhygiene";
	public final static String GROOMHYGFIRSTRADIO = "//input[@name='Grooming' and @value='1']";
	public final static String GROOMHYGSECONDRADIO = "//input[@name='Grooming' and @value='2']";
	public final static String GROOMHYGTHIRDRADIO = "//input[@name='Grooming' and @value='3']";
	public final static String GROOMHYGFOURTHRADIO = "//input[@name='Grooming' and @value='4']";
	public final static String TOINEXTBTN = "btn-toileting";
	public final static String TOIFIRSTRADIO = "//input[@name='Toileting' and @value='1']";
	public final static String TOISECONDRADIO = "//input[@name='Toileting' and @value='2']";
	public final static String TOITHIRDRADIO = "//input[@name='Toileting' and @value='3']";
	public final static String TOIFOURTHRADIO = "//input[@name='Toileting' and @value='4']";
	public final static String MEDNEXTBTN = "btn-medicationmanagement";
	public final static String MEDFIRSTRADIO = "//input[@name='Medication' and @value='1']";
	public final static String MEDSECONDRADIO = "//input[@name='Medication' and @value='2']";
	public final static String MEDTHIRDRADIO = "//input[@name='Medication' and @value='3']";
	public final static String MEDFOURTHRADIO = "//input[@name='Medication' and @value='4']";
	public final static String MEMNEXTBTN = "btn-memory";
	public final static String MEMFIRSTRADIO = "//input[@name='Memory' and @value='1']";
	public final static String MEMSECONDRADIO = "//input[@name='Memory' and @value='2']";
	public final static String MEMTHIRDRADIO = "//input[@name='Memory' and @value='3']";
	public final static String MEMFOURTHRADIO = "//input[@name='Memory' and @value='4']";
	public final static String EMBNEXTBTN = "btn-emotionsandbehavior";
	public final static String EMBFIRSTRADIO = "//input[@name='Emotions' and @value='1']";
	public final static String EMBSECONDRADIO = "//input[@name='Emotions' and @value='2']";
	public final static String EMBTHIRDRADIO = "//input[@name='Emotions' and @value='3']";
	public final static String EMBFOURTHRADIO = "//input[@name='Emotions' and @value='4']";
	public final static String SEARCHBTN = "//button[@type='submit']";
}
